services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - db

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://db:27017/mydatabase
      - PORT=3000
    depends_on:
      - db

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://db:27017/mydatabase
      - PORT=3000
    depends_on:
      - db

  db:
    image: mongo:5
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
